---
title: "Group 7 Porject Proposal"
author: "Group Members: Savannah Umali-Jepson, Sarah Peng, Lufei Wang, Ming Yan "
date: "5/1/2020"
output: html_document
---
## **Organ Donations**
### Outline:

#### What is the purpose of your research project?

* We want to compare the attitudes towards organ donations and transplants to the actual donation statistics to see if the correlation between support and action.


#### What other research has been done in this area? Make sure to include 3+ links to related works, as well as a summary of what that work has discovered.

* <https://www.organdonor.gov/sites/default/files/about-dot/files/nsodap-organ-donation-survey-2019.pdf>
    + This report describes the main findings from the 2019 National Survey of Organ Donation Attitudes and Practices (NSODAP). 

* <https://www.organdonor.gov/sites/default/files/about-dot/files/national-survey-organ-donation-2012.pdf>
    + The survey included measures of attitudes and behaviors related to donation of organs for transplantation, discussing donation wishes with family, granting permission to donate, beliefs about the donation process, and opinions on policies related to donation.

* <https://www.organdonor.gov/statistics-stories/statistics.html>
    + This report shows the situation of the system of organ donation including issues like shortage and basic statistics about the donors and recipients with visualizations. 


#### What is the dataset you'll be working with? 
* Table of Contents for Results Tables for the 2019 National Survey of Organ Donation Attitudes and Practices (NSODAP) <https://www.organdonor.gov/about-dot/grants/research-reports>
    + This dataset comes from the U.S. Department of Health and Human Services, Health Resources and Services Administration, Healthcare Systems Bureau, and the Division of Transplantation. It includes responses and demographics to an 86 question survey regarding people’s views on organ donation.

* Donors Recovered in the U.S. by Donor Type <https://optn.transplant.hrsa.gov/data/view-data-reports/national-data/#>
    + The second dataset is from the U.S. Department of Health & Human Services. The data was collected through an online database system which compiled from the Organ Procurement and Transplantation Network. It gives us the data statistics of different organs being donated in correlation to location, gender, age, and ethnicity, etc. 

#### Who is your target audience?  Depending on the domain of your data, there may be a variety of audiences interested in using the dataset. You should hone in on one of these audiences.

* Our target audience will be focused on the public, specifically people who are considering to be an organ donor. 

#### What should your audience learn from your resource? Please consider specific questions that your project can answer using the data you have identified (that are related to the overarching purpose)
*  Do people’s attitudes towards donation actually impact the likelihood of them donating?
*  Are there certain demographics that are more likely to donate?
*  Are there certain demographics that need more donations?
*  Are people more willing to do specific organ donations over others and if so which ones?
*  Have donations increased or decreased over time?
Has the need for donations increased or decreased over time?


### Technical Description:

#### What will be the format of your final product (Shiny app, HTML page, compiled .Rmd file, etc)?
*  We are planning on doing an HTML page

#### Do you anticipate any specific data collection / data management challenges?
*  Sorting through the data to determine which data is valuable
*  Merging data correctly
*  Dealing with missing data

#### What new technical skills will need to learn in order to complete your project?
*  New forms of visualizations
*  Better collaboration skills on GitHub
*  Formatting datasets
*  Analyzing papers

#### What major challenges do you anticipate? 
*  Communication
*  Working in remotely
*  Time of work

